// <auto-generated />
using System;
using DotNetMvcWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DotNetMvcWeb.Migrations
{
    /// <summary>
    /// 這是一份自動產生的設計師 (Designer) 檔案，記錄了 Seed Data 加入後的模型快照。
    /// 此檔案除了原本的資料表結構外，現在還多了 b.HasData(...) 來記錄我們所定義的預設資料。
    /// 藉由這個快照，EF Core 下次在比對時，就能知道這些 Seed Data 已經存在於模型中，不會重複產生 Insert 的 Migration。
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602082526_SeedOracleDemoData")]
    partial class SeedOracleDemoData
    {
        /// <summary>
        /// 包含了模型結構的定義，以及我們透過 HasData 設定的預設資料。
        /// 當 EF Core 需要知道目前的模型狀態時，會參考最新的 Designer 檔案中的這個方法。
        /// 可以看到下方除了 Property 定義外，還呼叫了 b.HasData() 注入實體。
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetMvcWeb.Models.OracleDemoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("OracleDemoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "這是第一筆透過 EF Core Seed 建立的測試資料。",
                            Name = "測試示範項目 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "示範如何在 Oracle 資料庫中儲存繁體中文內容。",
                            Name = "測試示範項目 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 2, 8, 25, 25, 881, DateTimeKind.Utc).AddTicks(6280),
                            Description = "可以嘗試在畫面上點擊編輯或刪除這筆資料，測試 HTMX 的互動效果！",
                            Name = "教學用項目"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
