// <auto-generated />
using System;
using DotNetMvcWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DotNetMvcWeb.Migrations
{
    /// <summary>
    /// 這是一份自動產生的設計師 (Designer) 檔案。
    /// EF Core 利用這個檔案來記錄「在建立此 Migration 當下，DbContext 所包含的所有模型設定與結構快照 (Snapshot)」。
    /// 這樣 EF Core 之後在產生下一個 Migration 時，就可以拿這個快照與目前的程式碼做對比，找出差異。
    /// 開發者通常不需要也不應該手動修改這個檔案。
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602081853_InitialOracleDemo")]
    partial class InitialOracleDemo
    {
        /// <summary>
        /// BuildTargetModel 方法負責建構這份 Migration 當下的完整模型快照。
        /// 裡面包含了所有的實體 (Entities)、屬性 (Properties)、資料型別對應 (ColumnTypes) 以及主外鍵關聯。
        /// 這個快照是 EF Core 內部比對狀態的重要依據。
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetMvcWeb.Models.OracleDemoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("OracleDemoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
