// <auto-generated />
// =====================================================================================================
// 【教學註解】ModelSnapshot 檔案
// 這個檔案是 EF Core 用來紀錄「目前」系統中所有 Model (實體) 的最終結構狀態快照 (Snapshot)。
// 每次新增 Migration 時，EF Core 就是拿您的 C# 程式碼與這個快照做比較，
// 藉此判斷出應該要在新的 Migration 檔案裡產生哪些變動 (例如新增欄位、改屬性等)。
// 請注意，這個檔案完全由工具自動維護，實務上「絕對不要」手動去修改它喔！
// =====================================================================================================

using System;
using DotNetMvcWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DotNetMvcWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetMvcWeb.Models.OracleDemoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("Id");

                    b.ToTable("OracleDemoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "這是第一筆透過 EF Core Seed 建立的測試資料。",
                            Name = "測試示範項目 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "示範如何在 Oracle 資料庫中儲存繁體中文內容。",
                            Name = "測試示範項目 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 2, 8, 25, 25, 881, DateTimeKind.Utc).AddTicks(6280),
                            Description = "可以嘗試在畫面上點擊編輯或刪除這筆資料，測試 HTMX 的互動效果！",
                            Name = "教學用項目"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
