// <auto-generated />
using System;
using DotNetMvcWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetMvcWeb.Migrations.MssqlDb
{
    [DbContext(typeof(MssqlDbContext))]
    [Migration("20260611035919_InitialMssqlDemo")]
    partial class InitialMssqlDemo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetMvcWeb.Models.MssqlDemoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MssqlDemoCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "一般"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "重要"
                        });
                });

            modelBuilder.Entity("DotNetMvcWeb.Models.MssqlDemoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MssqlDemoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "這是第一筆透過 EF Core Seed 建立的測試資料。",
                            Name = "測試示範項目 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "示範如何在 MSSQL 資料庫中儲存繁體中文內容。",
                            Name = "測試示範項目 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "可以嘗試在畫面上點擊編輯或刪除這筆資料，測試 HTMX 的互動效果！",
                            Name = "教學用項目"
                        });
                });

            modelBuilder.Entity("DotNetMvcWeb.Models.MssqlDemoItem", b =>
                {
                    b.HasOne("DotNetMvcWeb.Models.MssqlDemoCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotNetMvcWeb.Models.MssqlDemoCategory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
