name: dot-net-mvc-web
services:
  dot-net-mvc-web-mysql:
    image: mysql:9
    container_name: dot-net-mvc-web-mysql
    platform: linux/x86_64 # 關鍵！解決 Apple Silicon 有時遇到的架構相容問題
    restart: no
    ports:
      - "3307:3306" # mysql 預設 port 為 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: dot_net_mvc_web_db
      MYSQL_USER: dot-net-mvc-web
      MYSQL_PASSWORD: DotNetMvcWebAbc123
    volumes:
      - ./data:/var/lib/mysql